### ISSUE TITLE
Missing function?

### ISSUE THREAD

**Issue by mathieuboudreau** [MPUmri/RRIFT#2]
FYI: In your quickExample.m file, it appears to me that there is a function that's called that missing from your repo.

https://github.com/MPUmri/RRIFT/blob/8ff976d8bf9fdf3971c989f847ae1b9fc3e97aef/quickExample.m#L46

All the other scripts worked for me though.

**Comment by notZaki** [comment]
Thanks for checking the scripts!

That particular script shouldn't even be in the repository---it's supposed to be replaced by `a00_quickExample.m`.
The script will probably work if `ParkerAif` is replaced with `GeorgiouAif`, but the entire thing is better off being deleted anyways.

**Comment by mathieuboudreau** [comment]
That makes sense! A+

**Comment by notZaki** [comment]
@mathieuboudreau 
I noticed that you created a docker container with octave on your fork.
Does that mean you ran the code with octave or is that just a general dockerfile?
